[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Mango", email = ""},
]
dependencies = [
    "rich>=13.3.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}
